require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_modular_headers!
use_frameworks!

target 'TestApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TestAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'TestApp-tvOS' do
  # Pods for TestApp-tvOS

  target 'TestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
